rosbag record /ardrone_1/ego_planner_node/goal_point \
              /ardrone_1/ego_planner_node/global_list \
              /ardrone_1/ego_planner_node/optimal_list \
              /ardrone_1/ego_planner_node/a_star_list \
              /ardrone_1/ego_planner_node/init_list \
              /ardrone_2/ego_planner_node/goal_point \
              /ardrone_2/ego_planner_node/global_list \
              /ardrone_2/ego_planner_node/optimal_list \
              /ardrone_2/ego_planner_node/a_star_list \
              /ardrone_2/ego_planner_node/init_list \
              /ardrone_3/ego_planner_node/goal_point \
              /ardrone_3/ego_planner_node/global_list \
              /ardrone_3/ego_planner_node/optimal_list \
              /ardrone_3/ego_planner_node/a_star_list \
              /ardrone_3/ego_planner_node/init_list \
              /ardrone_4/ego_planner_node/goal_point \
              /ardrone_4/ego_planner_node/global_list \
              /ardrone_4/ego_planner_node/optimal_list \
              /ardrone_4/ego_planner_node/a_star_list \
              /ardrone_4/ego_planner_node/init_list \
              /ardrone_5/ego_planner_node/goal_point \
              /ardrone_5/ego_planner_node/global_list \
              /ardrone_5/ego_planner_node/optimal_list \
              /ardrone_5/ego_planner_node/a_star_list \
              /ardrone_5/ego_planner_node/init_list \
              /ardrone_1/grid_map/occupancy_inflate \
              /ardrone_1/grid_map/occupancy \
              /ardrone_2/grid_map/occupancy_inflate \
              /ardrone_2/grid_map/occupancy \
              /ardrone_3/grid_map/occupancy_inflate \
              /ardrone_3/grid_map/occupancy \
              /ardrone_4/grid_map/occupancy_inflate \
              /ardrone_4/grid_map/occupancy \
              /ardrone_5/grid_map/occupancy_inflate \
              /ardrone_5/grid_map/occupancy \
              /ardrone_1/vi_sensor/camera_depth/depth/disparity \
              /ardrone_2/vi_sensor/camera_depth/depth/disparity \
              /ardrone_3/vi_sensor/camera_depth/depth/disparity \
              /ardrone_4/vi_sensor/camera_depth/depth/disparity \
              /ardrone_5/vi_sensor/camera_depth/depth/disparity \
              /ardrone_1/tag_detections_image \
              /ardrone_2/tag_detections_image \
              /ardrone_3/tag_detections_image \
              /ardrone_4/tag_detections_image \
              /ardrone_5/tag_detections_image \
              /initial_tag_markers \
              /new_tag_markers \
              /ardrone_1/odom_visualization/robot \
              /ardrone_2/odom_visualization/robot \
              /ardrone_3/odom_visualization/robot \
              /ardrone_4/odom_visualization/robot \
              /ardrone_5/odom_visualization/robot \
