UWB_Anchors:
    - 
      id: 0
      x: 5
      y: 40 
      z: 0
    - 
      id: 1
      x: 6
      y: -14
      z: 0
    - 
      id: 2
      x: 17
      y: -1
      z: 0
    - 
      id: 3
      x: -10
      y: 3
      z: 0
    - 
      id: 4
      x: 10
      y: 25
      z: 0
    - 
      id: 5
      x: 20
      y: -22
      z: 0
    - 
      id: 6
      x: 6
      y: 19
      z: 0
    - 
      id: 7
      x: -5
      y: 28
      z: 0
    - 
      id: 8
      x: 23
      y: 14
      z: 0
    - 
      id: 9
      x: 11
      y: -33
      z: 0
    - 
      id: 10
      x: 2.7
      y: 0
      z: 0.5