UWB_Anchors:
  - id: 0
    x: -23
    y: -23
    z: 0.7

  - id: 1
    x: -23
    y: -5
    z: 0.7

  - id: 2
    x: -23
    y: 8
    z: 0.7

  - id: 3
    x: -23
    y: 23
    z: 0.7

  - id: 4
    x: -12
    y: -23
    z: 0.7

  - id: 5
    x: -6
    y: -23
    z: 0.7

  - id: 6
    x: 6
    y: -23
    z: 0.7

  - id: 7
    x: 12
    y: -23
    z: 0.7

  - id: 8
    x: 23
    y: -23
    z: 0.7

  - id: 9
    x: 23
    y: -10
    z: 0.7

  - id: 10
    x: 23
    y: 0
    z: 0.7

  - id: 11
    x: 23
    y: 10
    z: 0.7

  - id: 12
    x: 23
    y: 23
    z: 0.7

  - id: 13
    x: 12
    y: 23
    z: 0.7

  - id: 14
    x: -12
    y: 23
    z: 0.7

  - id: 15
    x: 0
    y: 23
    z: 0.7

  - id: 16
    x: 0
    y: 16
    z: 0.7

  - id: 17
    x: -16
    y: 18
    z: 0.7

  - id: 18
    x: 18
    y: 18
    z: 0.7

  - id: 19
    x: 0
    y: -16
    z: 0.7