UWB_Anchors:
    -
      id: 0
      x: -23
      y: 9
      z: 0.7
    -
      id: 1
      x: -23
      y: -3
      z: 0.7
    -
      id: 2
      x: -23
      y: -17
      z: 0.7
    -
      id: 3
      x: -14
      y: 17
      z: 0.7
    -
      id: 4
      x: -15
      y: 8
      z: 0.7
    -
      id: 5
      x: -12
      y: -2
      z: 0.7
    -
      id: 6
      x: -12
      y: -22
      z: 0.7
    -
      id: 7
      x: -8
      y: 10
      z: 0.7
    -
      id: 8
      x: -2
      y: 16
      z: 0.7
    -
      id: 9
      x: -3
      y: 5
      z: 0.7
    -
      id: 10
      x: -2
      y: -2
      z: 0.7
    -
      id: 11
      x: 2
      y: -10
      z: 0.7
    -
      id: 12
      x: 5
      y: 1
      z: 0.7
    -
      id: 13
      x: 4
      y: -21
      z: 0.7
    -
      id: 14
      x: 13
      y: 24
      z: 0.7
    -
      id: 15
      x: 12
      y: 16
      z: 0.7
    -
      id: 16
      x: 14
      y: 2
      z: 0.7
    -
      id: 17
      x: 15
      y: -11
      z: 0.7
    -
      id: 18
      x: 21
      y: 24
      z: 0.7
    -
      id: 19
      x: 21
      y: 4
      z: 0.7